---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - my_clickhouse
- name: Install Vector standalone
  hosts: vector
  roles:
    - vector-role
- name: Install lighthouse and Nginx
  hosts: lighthouse
  roles:
    - lighthouse-role